/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ediwo
 */
public class jfMain extends javax.swing.JFrame {

    /**
     * Creates new form jfMain
     */
    
    public jfMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfstudentid = new javax.swing.JTextField();
        tfstudentlastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfstudentname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tfattendancescoreequivalent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfattendancescore = new javax.swing.JTextField();
        tfattendancescorepercent = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tfwrittenquizscoreequivalent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfwrittenquizscore = new javax.swing.JTextField();
        tfwrittenquizscorepercent = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tfpracticalquizscoreequivalent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfpracticalquizscore = new javax.swing.JTextField();
        tfpracticalquizscorepercent = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        tfprojectscoreequivalent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfprojectscore = new javax.swing.JTextField();
        tfprojectscorepercent = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        tfprelimexamscoreequivalent = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfprelimexamscore = new javax.swing.JTextField();
        tfprelimexamscorepercent = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        tfremarks = new javax.swing.JTextField();
        tfprelimgrade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbnew = new javax.swing.JButton();
        jbcompute = new javax.swing.JButton();
        jbexit = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jLabel30.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel30.setText("50");

        jLabel31.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel31.setText("EG");

        jLabel32.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel32.setText("10%");

        jLabel36.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel36.setText("50");

        jLabel37.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel37.setText("EG");

        jLabel38.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel38.setText("20%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grading System");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("STUDENT RECORD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("STUDENT ID: ");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Firstname: ");

        tfstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstudentidActionPerformed(evt);
            }
        });

        tfstudentlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstudentlastnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Lastname:");

        tfstudentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstudentnameActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        tfattendancescoreequivalent.setEditable(false);
        tfattendancescoreequivalent.setBackground(new java.awt.Color(51, 255, 51));
        tfattendancescoreequivalent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Score: ");

        tfattendancescore.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tfattendancescore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfattendancescoreFocusLost(evt);
            }
        });
        tfattendancescore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfattendancescoreActionPerformed(evt);
            }
        });

        tfattendancescorepercent.setEditable(false);
        tfattendancescorepercent.setBackground(new java.awt.Color(51, 255, 51));
        tfattendancescorepercent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel24.setText("20 ");

        jLabel25.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel25.setText("EG");

        jLabel26.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel26.setText("10%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfattendancescore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tfattendancescoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfattendancescorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfattendancescore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfattendancescoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfattendancescorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Written Quiz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        tfwrittenquizscoreequivalent.setEditable(false);
        tfwrittenquizscoreequivalent.setBackground(new java.awt.Color(51, 255, 51));
        tfwrittenquizscoreequivalent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Score: ");

        tfwrittenquizscore.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tfwrittenquizscore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfwrittenquizscoreFocusLost(evt);
            }
        });

        tfwrittenquizscorepercent.setEditable(false);
        tfwrittenquizscorepercent.setBackground(new java.awt.Color(51, 255, 51));
        tfwrittenquizscorepercent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel27.setText("50");

        jLabel29.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel29.setText("10%");

        jLabel28.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel28.setText("EG");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(tfwrittenquizscore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfwrittenquizscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfwrittenquizscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel28)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel29)
                        .addGap(24, 24, 24))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfwrittenquizscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfwrittenquizscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfwrittenquizscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Practical Quiz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        tfpracticalquizscoreequivalent.setEditable(false);
        tfpracticalquizscoreequivalent.setBackground(new java.awt.Color(51, 255, 51));
        tfpracticalquizscoreequivalent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Score: ");

        tfpracticalquizscore.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tfpracticalquizscore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfpracticalquizscoreFocusLost(evt);
            }
        });

        tfpracticalquizscorepercent.setEditable(false);
        tfpracticalquizscorepercent.setBackground(new java.awt.Color(51, 255, 51));
        tfpracticalquizscorepercent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel35.setText("20%");

        jLabel34.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel34.setText("EG");

        jLabel33.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel33.setText("50");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfpracticalquizscore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfpracticalquizscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfpracticalquizscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(60, 60, 60)
                .addComponent(jLabel34)
                .addGap(46, 46, 46)
                .addComponent(jLabel35)
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpracticalquizscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpracticalquizscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpracticalquizscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        tfprojectscoreequivalent.setEditable(false);
        tfprojectscoreequivalent.setBackground(new java.awt.Color(51, 255, 51));
        tfprojectscoreequivalent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Score: ");

        tfprojectscore.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tfprojectscore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfprojectscoreFocusLost(evt);
            }
        });

        tfprojectscorepercent.setEditable(false);
        tfprojectscorepercent.setBackground(new java.awt.Color(51, 255, 51));
        tfprojectscorepercent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel40.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel40.setText("EG");

        jLabel39.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel39.setText("100");

        jLabel41.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel41.setText("30%");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(tfprojectscore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfprojectscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfprojectscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel40)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfprojectscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprojectscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprojectscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(204, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prelim Exam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        tfprelimexamscoreequivalent.setEditable(false);
        tfprelimexamscoreequivalent.setBackground(new java.awt.Color(51, 255, 51));
        tfprelimexamscoreequivalent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Score: ");

        tfprelimexamscore.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tfprelimexamscore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfprelimexamscoreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfprelimexamscoreFocusLost(evt);
            }
        });
        tfprelimexamscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprelimexamscoreActionPerformed(evt);
            }
        });

        tfprelimexamscorepercent.setEditable(false);
        tfprelimexamscorepercent.setBackground(new java.awt.Color(51, 255, 51));
        tfprelimexamscorepercent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel44.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel44.setText("30%");

        jLabel43.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel43.setText("EG");

        jLabel42.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel42.setText("100");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfprelimexamscore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfprelimexamscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfprelimexamscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel43)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel44)
                        .addGap(17, 17, 17))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfprelimexamscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprelimexamscoreequivalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprelimexamscorepercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(204, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("PRELIM COMPUTED"));

        tfremarks.setEditable(false);
        tfremarks.setBackground(new java.awt.Color(51, 255, 51));
        tfremarks.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        tfremarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfremarksActionPerformed(evt);
            }
        });

        tfprelimgrade.setEditable(false);
        tfprelimgrade.setBackground(new java.awt.Color(51, 255, 51));
        tfprelimgrade.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        tfprelimgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprelimgradeActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel23.setText("Remarks: ");

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setText("Prelim Grade: ");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(tfprelimgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfremarks))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfremarks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfprelimgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jbnew.setText("New");
        jbnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnewActionPerformed(evt);
            }
        });

        jbcompute.setText("Compute Grades");
        jbcompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcomputeActionPerformed(evt);
            }
        });

        jbexit.setText("Exit");
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbnew, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbcompute, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfstudentlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfstudentlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnew)
                    .addComponent(jbcompute)
                    .addComponent(jbexit))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstudentidActionPerformed

    private void tfstudentlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstudentlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstudentlastnameActionPerformed

    private void tfstudentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstudentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstudentnameActionPerformed

    private void tfprelimgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprelimgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprelimgradeActionPerformed

    private void tfremarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfremarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfremarksActionPerformed

    private void tfattendancescoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfattendancescoreFocusLost
        // TODO add your handling code here:
        Double score, equiv, equiv2;
        score = Double.parseDouble(tfattendancescore.getText());
        
        if(score > 20){
            equiv = 20.0 / 20;
            equiv2 = equiv * 10;
            
            tfattendancescore.setText("20");
            tfattendancescoreequivalent.setText(String.valueOf(equiv2 * 10));
            tfattendancescorepercent.setText(String.valueOf(equiv2));
        }
        else{
            equiv = score / 20;
            equiv2 = equiv * 10;
            
            tfattendancescoreequivalent.setText(String.valueOf(equiv2 * 10));
            tfattendancescorepercent.setText(String.valueOf(equiv2));
        }
    }//GEN-LAST:event_tfattendancescoreFocusLost

    private void tfattendancescoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfattendancescoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfattendancescoreActionPerformed

    private void tfwrittenquizscoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfwrittenquizscoreFocusLost
        // TODO add your handling code here:
        Double score, equiv, equiv2;
        score = Double.parseDouble(tfwrittenquizscore.getText());
        
        if(score > 50){
            equiv = 50.0 / 50;
            equiv2 = equiv * 10;
        
            tfwrittenquizscore.setText("50");
            tfwrittenquizscoreequivalent.setText(String.valueOf(equiv2 * 10));
            tfwrittenquizscorepercent.setText(String.valueOf(equiv2));
        }
        else{
            equiv = score / 50;
            equiv2 = equiv * 10;
        
            tfwrittenquizscoreequivalent.setText(String.valueOf(equiv2 * 10));
            tfwrittenquizscorepercent.setText(String.valueOf(equiv2));
        }
    }//GEN-LAST:event_tfwrittenquizscoreFocusLost

    private void tfpracticalquizscoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfpracticalquizscoreFocusLost
        // TODO add your handling code here:
        Double score, equiv, equiv2, equiv3;
        score = Double.parseDouble(tfpracticalquizscore.getText());
        
        if(score > 50){
            equiv = 50.0 / 50;
            equiv2 = equiv * 20;
            equiv3 = equiv * 100;
        
            tfpracticalquizscore.setText("50");
            tfpracticalquizscoreequivalent.setText(String.valueOf(equiv3));
            tfpracticalquizscorepercent.setText(String.valueOf(equiv2));
        }
        else{
            equiv = score / 50;
            equiv2 = equiv * 20;
            equiv3 = equiv * 100;
        
            tfpracticalquizscoreequivalent.setText(String.valueOf(equiv3));
            tfpracticalquizscorepercent.setText(String.valueOf(equiv2));
        }
    }//GEN-LAST:event_tfpracticalquizscoreFocusLost

    private void tfprojectscoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfprojectscoreFocusLost
        // TODO add your handling code here:
        Double score, equiv, equiv2, equiv3;
        score = Double.parseDouble(tfprojectscore.getText());
        
        if(score > 100){
            equiv = 100.0 / 100;
            equiv2 = equiv * 30;
            equiv3 = equiv * 100;
        
            tfprojectscore.setText("100");
            tfprojectscoreequivalent.setText(String.valueOf(equiv3));
            tfprojectscorepercent.setText(String.valueOf(equiv2));
        }
        else{
            equiv = score / 100;
            equiv2 = equiv * 30;
            equiv3 = equiv * 100;
        
            tfprojectscoreequivalent.setText(String.valueOf(equiv3));
            tfprojectscorepercent.setText(String.valueOf(equiv2));
        }
    }//GEN-LAST:event_tfprojectscoreFocusLost

    private void tfprelimexamscoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfprelimexamscoreFocusLost
        // TODO add your handling code here:
        Double score, equiv, equiv2, equiv3;
        score = Double.parseDouble(tfprelimexamscore.getText());
        
        if(score > 100){
            equiv = 100.0 / 100;
            equiv2 = equiv * 30;
            equiv3 = equiv * 100;
        
            tfprelimexamscore.setText("100");
            tfprelimexamscoreequivalent.setText(String.valueOf(equiv3));
            tfprelimexamscorepercent.setText(String.valueOf(equiv2));
        }
        else{
            equiv = score / 100;
            equiv2 = equiv * 30;
            equiv3 = equiv * 100;
        
            
            tfprelimexamscoreequivalent.setText(String.valueOf(equiv3));
            tfprelimexamscorepercent.setText(String.valueOf(equiv2));
        }
        
        
    }//GEN-LAST:event_tfprelimexamscoreFocusLost

    private void jbcomputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcomputeActionPerformed
        // TODO add your handling code here:
        Double attendance = Double.parseDouble(tfattendancescorepercent.getText());
        Double written = Double.parseDouble(tfwrittenquizscorepercent.getText());
        Double practical = Double.parseDouble(tfpracticalquizscorepercent.getText());
        Double project = Double.parseDouble(tfprojectscorepercent.getText());
        Double prelim = Double.parseDouble(tfprelimexamscorepercent.getText());
        
        Double total = attendance + written + practical + project + prelim;
        
        tfprelimgrade.setText(String.valueOf(total));
        
        if(total < 75){
            tfremarks.setText("Failed");
        }
        else{
            tfremarks.setText("Passed");
        }
       
    }//GEN-LAST:event_jbcomputeActionPerformed

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbexitActionPerformed

    private void jbnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnewActionPerformed
        this.dispose();
        new jfMain().setVisible(true);
    }//GEN-LAST:event_jbnewActionPerformed

    private void tfprelimexamscoreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfprelimexamscoreFocusGained
        
    }//GEN-LAST:event_tfprelimexamscoreFocusGained

    private void tfprelimexamscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprelimexamscoreActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_tfprelimexamscoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMain().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbcompute;
    private javax.swing.JButton jbexit;
    private javax.swing.JButton jbnew;
    private javax.swing.JTextField tfattendancescore;
    private javax.swing.JTextField tfattendancescore1;
    private javax.swing.JTextField tfattendancescore2;
    private javax.swing.JTextField tfattendancescore3;
    private javax.swing.JTextField tfattendancescore4;
    private javax.swing.JTextField tfattendancescore5;
    private javax.swing.JTextField tfattendancescoreequivalent;
    private javax.swing.JTextField tfattendancescoreequivalent1;
    private javax.swing.JTextField tfattendancescoreequivalent2;
    private javax.swing.JTextField tfattendancescoreequivalent3;
    private javax.swing.JTextField tfattendancescoreequivalent4;
    private javax.swing.JTextField tfattendancescoreequivalent5;
    private javax.swing.JTextField tfattendancescorepercent;
    private javax.swing.JTextField tfattendancescorepercent1;
    private javax.swing.JTextField tfattendancescorepercent2;
    private javax.swing.JTextField tfattendancescorepercent3;
    private javax.swing.JTextField tfattendancescorepercent4;
    private javax.swing.JTextField tfattendancescorepercent5;
    private javax.swing.JTextField tfpracticalquizscore;
    private javax.swing.JTextField tfpracticalquizscoreequivalent;
    private javax.swing.JTextField tfpracticalquizscorepercent;
    private javax.swing.JTextField tfprelimexamscore;
    private javax.swing.JTextField tfprelimexamscoreequivalent;
    private javax.swing.JTextField tfprelimexamscorepercent;
    private javax.swing.JTextField tfprelimgrade;
    private javax.swing.JTextField tfprojectescoreequivalent1;
    private javax.swing.JTextField tfprojectescoreequivalent2;
    private javax.swing.JTextField tfprojectescoreequivalent3;
    private javax.swing.JTextField tfprojectescoreequivalent4;
    private javax.swing.JTextField tfprojectscore;
    private javax.swing.JTextField tfprojectscore1;
    private javax.swing.JTextField tfprojectscore2;
    private javax.swing.JTextField tfprojectscore3;
    private javax.swing.JTextField tfprojectscore4;
    private javax.swing.JTextField tfprojectscoreequivalent;
    private javax.swing.JTextField tfprojectscorepercent;
    private javax.swing.JTextField tfprojectscorepercent1;
    private javax.swing.JTextField tfprojectscorepercent2;
    private javax.swing.JTextField tfprojectscorepercent3;
    private javax.swing.JTextField tfprojectscorepercent4;
    private javax.swing.JTextField tfremarks;
    private javax.swing.JTextField tfscore1;
    private javax.swing.JTextField tfscore2;
    private javax.swing.JTextField tfscore3;
    private javax.swing.JTextField tfscoreequivalent1;
    private javax.swing.JTextField tfscoreequivalent2;
    private javax.swing.JTextField tfscoreequivalent3;
    private javax.swing.JTextField tfscorepercent1;
    private javax.swing.JTextField tfscorepercent2;
    private javax.swing.JTextField tfscorepercent3;
    private javax.swing.JTextField tfstudentid;
    private javax.swing.JTextField tfstudentlastname;
    private javax.swing.JTextField tfstudentname;
    private javax.swing.JTextField tfwrittenquizscore;
    private javax.swing.JTextField tfwrittenquizscoreequivalent;
    private javax.swing.JTextField tfwrittenquizscorepercent;
    // End of variables declaration//GEN-END:variables
}
